### ISSUE TITLE
Can't build this project on LLVM 15

### ISSUE THREAD

**Issue by ouliuquan** [MaxXSoft/YuLang#2]
你好,我在Ubuntu LLVM 15上编译，发现一个generator.cpp 187 行getPointerElementType函数被删除的问题，即使改成了getNonOpaquePointerElementType也不行，因为[官方明确说删除掉](https://reviews.llvm.org/D117885?id=402538)，且没有代替函数，请帮忙看看怎么修改，超出了本人能力范围。

Hello, I compiled on Ubuntu LLVM 15, and found a problem that the getPointerElementType function in line 187 of generator.cpp was deleted, even if it was changed to getNonOpaquePointerElementType, it would not work, because the official clearly stated that [it was deleted](https://reviews.llvm.org/D117885?id=402538), and there was no replacement function, please help to see how Modifications are beyond the scope of my ability.

**Comment by MaxXSoft** [comment]
你好! 目前的 YuLang 在适配 LLVM 15 时确实有一些问题, 稍后我会就该问题做出一些修复. 感谢你的反馈!

Hello! Currently YuLang does have some issues when compiling with LLVM 15, and I'll be working on some fixes for that later. Thanks for your feedback!

**Comment by MaxXSoft** [comment]
Fixed in commit 2f573a2e6b7d80b38c02cdd2a6fff6186fb99506, 34ff43a209c32ede47caa32163b4413b3355b72f, 35b967f534bff8165a9a448f87690a399894011f, b3998d50b1030c6c155c0af9f601628160891268, 73a43937154b0c48cdde469411f9abd496ec39f3, 5f72355cc741e27cb730cb1b27c9257f5b28c5d2, e709e3e164a038976f6dc2f149d7fe69f303814f and e7292765a43c7d04cb1801bb4a7153e644d98616.

Now supported up to LLVM 16.
